package com.yk.tools.pm.image.metadata;

import java.util.HashMap;
import java.util.Map;

/**
 * Sony ZV-E1 photos have a lot of metadata, so I moved them into a separate class.
 */
final class SonyZV_E1_MetadataSample {

  private SonyZV_E1_MetadataSample() {
    throw new AssertionError("Instance is not allowed.");
  }

  static Map<String, String> getSonyZVE1Metadata() {
    Map<String, String> metadata = new HashMap<>();
    metadata.put("AF Point Selected", "Center");
    metadata.put("Anti Blur", "On (Shooting)");
    metadata.put("Auto Portrait Framing", "No");
    metadata.put("Brightness", "0");
    metadata.put("Brightness Value", "-4.338");
    metadata.put("Color Compensation Filter", "0");
    metadata.put("Color Mode", "Unknown (255)");
    metadata.put("Color Mode Setting", "Off");
    metadata.put("Color Space", "sRGB");
    metadata.put("Color Temperature", "Auto");
    metadata.put("Component 1", "Y component: Quantization table 0, Sampling factors 2 horiz/1 vert");
    metadata.put("Component 2", "Cb component: Quantization table 1, Sampling factors 1 horiz/1 vert");
    metadata.put("Component 3", "Cr component: Quantization table 1, Sampling factors 1 horiz/1 vert");
    metadata.put("Components Configuration", "YCbCr");
    metadata.put("Compressed Bits Per Pixel", "5 bits/pixel");
    metadata.put("Compression", "JPEG (old-style)");
    metadata.put("Compression Type", "Baseline");
    metadata.put("Contrast", "0");
    metadata.put("Custom Rendered", "Normal process");
    metadata.put("Data Precision", "8 bits");
    metadata.put("Date/Time", "2025:02:01 00:46:59");
    metadata.put("Date/Time Digitized", "2025:02:01 00:46:59");
    metadata.put("Date/Time Original", "2025:02:01 00:46:59");
    metadata.put("Detected File Type Long Name", "Joint Photographic Experts Group");
    metadata.put("Detected File Type Name", "JPEG");
    metadata.put("Detected MIME Type", "image/jpeg");
    metadata.put("Digital Zoom Ratio", "1");
    metadata.put("Distortion Correction", "Auto");
    metadata.put("Dynamic Range Optimizer", "1");
    metadata.put("Exif Image Height", "2384 pixels");
    metadata.put("Exif Image Width", "4240 pixels");
    metadata.put("Exif Version", "2.32");
    metadata.put("Expected File Name Extension", "jpg");
    metadata.put("Exposure Bias Value", "0 EV");
    metadata.put("Exposure Mode", "Auto");
    metadata.put("Exposure Program", "Program normal");
    metadata.put("Exposure Time", "1/30 sec");
    metadata.put("F-Number", "f/4.0");
    metadata.put("File Format", "4 0 1 0");
    metadata.put("File Modified Date", "Sat Feb 01 00:46:59 +01:00 2025");
    metadata.put("File Name", "ZV-E1-1.JPG");
    metadata.put("File Size", "7525812 bytes");
    metadata.put("File Source", "Digital Still Camera (DSC)");
    metadata.put("Flash", "Flash did not fire");
    metadata.put("Flash Exposure Compensation", "0 EV");
    metadata.put("Flash Level", "Normal");
    metadata.put("Flash Status", "No flash present");
    metadata.put("FlashPix Version", "1.00");
    metadata.put("Focal Length", "28 mm");
    metadata.put("Focal Length 35", "28 mm");
    metadata.put("Focus Mode", "AF-S");
    metadata.put("Full Image Size", "2384 4240");
    metadata.put("HDR", "0");
    metadata.put("High ISO Noise Reduction", "65535");
    metadata.put("ISO Speed Ratings", "12800");
    metadata.put("Image Height", "2384 pixels");
    metadata.put("Image Quality", "Extra Fine");
    metadata.put("Image Stabilisation", "On");
    metadata.put("Image Width", "4240 pixels");
    metadata.put("Intelligent Auto", "1");
    metadata.put("Internal Serial Number", "000000000000");
    metadata.put("Interoperability Index", "Recommended Exif Interoperability Rules (ExifR98)");
    metadata.put("Interoperability Version", "1.00");
    metadata.put("Lateral Chromatic Aberration", "Auto");
    metadata.put("Lens ID", "65535");
    metadata.put("Lens Model", "FE 28-60mm F4-5.6");
    metadata.put("Lens Spec", "2 0 40 0 96 64 86 0");
    metadata.put("Lens Specification", "28-60mm f/4.0-5.6");
    metadata.put("Long Exposure Noise Reduction", "0");
    metadata.put("Make", "SONY");
    metadata.put("Max Aperture Value", "f/4.0");
    metadata.put("Metering Mode", "Multi-segment");
    metadata.put("Model", "ZV-E1");
    metadata.put("Multi Frame Noise Reduction", "0");
    metadata.put("Number of Components", "3");
    metadata.put("Number of Tables", "4 Huffman tables");
    metadata.put("Orientation", "Top, left side (Horizontal / normal)");
    metadata.put("Picture Effect", "Off");
    metadata.put("Preview Image Size", "1080 1920");
    metadata.put("PrintIM Version", "0300");
    metadata.put("Rating", "0");
    metadata.put("Recommended Exposure Index", "12800");
    metadata.put("Release Mode", "Normal");
    metadata.put("Resolution Unit", "Inch");
    metadata.put("Saturation", "0");
    metadata.put("Scene Capture Type", "Standard");
    metadata.put("Scene Mode", "Auto");
    metadata.put("Scene Type", "Directly photographed image");
    metadata.put("Sensitivity Type", "Recommended Exposure Index");
    metadata.put("Sequence Number", "Single");
    metadata.put("Sharpness", "4");
    metadata.put("Shutter", "65280 255 41");
    metadata.put("Shutter Count", "209715200");
    metadata.put("Soft Skin Effect", "Off");
    metadata.put("Software", "ZV-E1 v1.03");
    metadata.put("Sony Exposure Time", "1/0");
    metadata.put("Sony F Number", "0");
    metadata.put("Sony Model ID", "Unknown (393)");
    metadata.put("Sub-Sec Time", "758");
    metadata.put("Sub-Sec Time Digitized", "758");
    metadata.put("Sub-Sec Time Original", "758");
    metadata.put("Thumbnail Length", "7395 bytes");
    metadata.put("Thumbnail Offset", "39582 bytes");
    metadata.put("Time Zone", "+02:00");
    metadata.put("Time Zone Digitized", "+02:00");
    metadata.put("Time Zone Original", "+02:00");
    metadata.put("Unknown tag (0x0002)", "0x00000001");
    metadata.put("Unknown tag (0x0003)", "0x00000022");
    metadata.put("Unknown tag (0x0101)", "0x00000000");
    metadata.put("Unknown tag (0x2000)", "0");
    metadata.put("Unknown tag (0x2003)", "");
    metadata.put("Unknown tag (0x200d)", "1");
    metadata.put("Unknown tag (0x2015)", "65535");
    metadata.put("Unknown tag (0x2017)", "0");
    metadata.put("Unknown tag (0x2018)", "0");
    metadata.put("Unknown tag (0x2019)", "0");
    metadata.put("Unknown tag (0x201a)", "0");
    metadata.put("Unknown tag (0x201c)", "11");
    metadata.put("Unknown tag (0x201d)", "0 0");
    metadata.put("Unknown tag (0x201f)", "0 0 4 0");
    metadata.put("Unknown tag (0x2020)", "0 0 0 0 0 0 0 0 0 0");
    metadata.put("Unknown tag (0x2021)", "0");
    metadata.put("Unknown tag (0x2023)", "0");
    metadata.put("Unknown tag (0x2025)", "0 0 0 0");
    metadata.put("Unknown tag (0x2026)", "0 0");
    metadata.put("Unknown tag (0x2027)", "4240 2384 2789 1658");
    metadata.put("Unknown tag (0x2028)", "65535 65535");
    metadata.put("Unknown tag (0x2029)", "65535");
    metadata.put("Unknown tag (0x202a)", "[66 values]");
    metadata.put("Unknown tag (0x202b)", "0");
    metadata.put("Unknown tag (0x202c)", "256");
    metadata.put("Unknown tag (0x202d)", "0");
    metadata.put("Unknown tag (0x202e)", "0 3");
    metadata.put("Unknown tag (0x202f)", "0 0 0 0 0 0");
    metadata.put("Unknown tag (0x2032)", "0");
    metadata.put("Unknown tag (0x2033)", "0");
    metadata.put("Unknown tag (0x2034)", "0");
    metadata.put("Unknown tag (0x2035)", "3");
    metadata.put("Unknown tag (0x2036)", "1");
    metadata.put("Unknown tag (0x2037)", "151 2 206 1 1 1");
    metadata.put("Unknown tag (0x2038)", "0");
    metadata.put("Unknown tag (0x2039)", "0");
    metadata.put("Unknown tag (0x203a)", "[32 values]");
    metadata.put("Unknown tag (0x203c)", "[26 values]");
    metadata.put("Unknown tag (0x203d)", "6248");
    metadata.put("Unknown tag (0x203e)", "0");
    metadata.put("Unknown tag (0x203f)", "16186");
    metadata.put("Unknown tag (0x2041)", "0");
    metadata.put("Unknown tag (0x2044)", "7000052 53248");
    metadata.put("Unknown tag (0x5001)", "0");
    metadata.put("Unknown tag (0x5002)", "128");
    metadata.put("Unknown tag (0x9400)", "[456 values]");
    metadata.put("Unknown tag (0x9401)", "[7840 values]");
    metadata.put("Unknown tag (0x9402)", "[400 values]");
    metadata.put("Unknown tag (0x9403)", "152 35 0 0");
    metadata.put("Unknown tag (0x9404)", "[100 values]");
    metadata.put("Unknown tag (0x9406)", "[64 values]");
    metadata.put("Unknown tag (0x9408)", "[2780 values]");
    metadata.put("Unknown tag (0x940a)", "[2176 values]");
    metadata.put("Unknown tag (0x940b)", "[400 values]");
    metadata.put("Unknown tag (0x940c)", "[64 values]");
    metadata.put("Unknown tag (0x940d)", "172 74 0 0");
    metadata.put("Unknown tag (0x940e)", "[10752 values]");
    metadata.put("Unknown tag (0x940f)", "[4464 values]");
    metadata.put("Unknown tag (0x9412)", "[160 values]");
    metadata.put("Unknown tag (0x9413)", "[1024 values]");
    metadata.put("Unknown tag (0x9414)", "[1024 values]");
    metadata.put("Unknown tag (0x9416)", "[4416 values]");
    metadata.put("Unknown tag (0xa460)", "0");
    metadata.put("Unknown tag (0xb045)", "0");
    metadata.put("Unknown tag (0xb046)", "0");
    metadata.put("Unknown tag (0xb04c)", "1");
    metadata.put("Unknown tag (0xb04d)", "0");
    metadata.put("Unknown tag (0xb051)", "0");
    metadata.put("Unknown tag (0xb053)", "0");
    metadata.put("User Comment", "");
    metadata.put("Vignetting Correction", "Auto");
    metadata.put("WB Shift Amber/Magenta", "0 0");
    metadata.put("White Balance", "Auto");
    metadata.put("White Balance 2", "0");
    metadata.put("White Balance Fine Tune Value", "0");
    metadata.put("White Balance Mode", "Auto white balance");
    metadata.put("X Resolution", "72 dots per inch");
    metadata.put("XMP Value Count", "1");
    metadata.put("Y Resolution", "72 dots per inch");
    metadata.put("YCbCr Positioning", "Datum point");
    metadata.put("Zone Matching", "ISO Setting Used");
    return metadata;
  }

}
